sudo: false
os: linux
language: elm
node_js: "10"
elm:
  - 0.19.0

install:
  - npm install

script:
  - npx elm-test
  - travis_retry npm run build
deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  local_dir: dist
  on:
    branch: master
